# Generated by Django 3.1.1 on 2020-10-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog_food_masterchef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkInBooking',
            field=models.CharField(max_length=12),
        ),
    ]
