# Generated by Django 3.1.1 on 2020-10-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201010_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkInBooking',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='timeBooking',
            field=models.TimeField(),
        ),
    ]
