# Generated by Django 3.1.1 on 2020-10-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201010_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkInBooking',
            field=models.DateTimeField(),
        ),
    ]
