# Generated by Django 3.1.1 on 2020-10-10 03:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201010_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='timePost',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='updatedPost',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='avatarBlog',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='contentBlog',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='avatarFood',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
