# Generated by Django 3.1.1 on 2020-10-12 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_dangnhap'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DangNhap',
        ),
    ]
