# Generated by Django 3.1.1 on 2020-10-13 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameTypeFood', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='food',
            name='nameTypeFood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.typefood'),
        ),
    ]
