# Generated by Django 3.1.1 on 2020-10-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20201013_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='numberOfGuest',
            field=models.IntegerField(default=0),
        ),
    ]
