# Generated by Django 3.1.2 on 2020-10-17 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_avatarusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('fullnameUser', models.CharField(max_length=100)),
                ('dobUser', models.DateField()),
                ('emailUser', models.CharField(max_length=100)),
                ('addressUSer', models.CharField(max_length=100)),
                ('avatarUser', models.ImageField(upload_to='images/users/')),
                ('statusUser', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='avatarUsers',
        ),
    ]
