# Generated by Django 3.1.2 on 2020-10-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20201017_0937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='user',
            name='phoneUser',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
