# Generated by Django 3.1.2 on 2020-10-17 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20201017_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='passwordUser',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='usernameUser',
        ),
    ]
